### ISSUE TITLE
spreadsheet.py 의 main 함수 분리

### ISSUE THREAD

**Issue by keonly** [NewWays-TechForImpactKAIST/main#37]
## 문제 상황
현재 `spreadsheet.py` 의 `main` 함수 내부에는 각 의회의 `ScrapBasicArguments` 데이터, `euc_kr` 적용 여부, 그리고 `scrap_XX` 함수의 존재 여부를 나타내는 `special_functions` 가 존재하고 있으며, 임의의 기초의회 번호를 스크랩하는 로직도 포함되어 있어, 단일책임원칙을 위배 중입니다.

## 해결 방안 제안
- `ScrapBasicArguments`를 `config.yaml` 등으로 분리하여 저장
  - 이 때 `euc_kr` 이나 `special_functions` 역시 굳이 별개의 정보로 저장하는 대신 `config.yaml` 내부에 함께 저장하면 좋을 것 같습니다.
```yaml
# 예시
args:
  6:
    euc_kr: True
    special_function: True
  57:
    pf_elt: div
    pf_cls: box
    name_elt: p
    name_cls: mem_tit2
    pty_elt: p
    pty_cls: mem_tit2
```
- `spreadsheet.py`의 경우 `utils` 디렉토리에 있으므로, 해당 파일 내부에서 `main` 함수를 통해 전체 스크래핑을 진행하기보다는, Google Sheet에 접근하여 주어진 의회 번호의 URL을 반환하는 정도의 함수만 존재하면 좋을 것 같습니다.
  - 기존의 스크래핑 로직은 `scrap/run.py` 처럼 별개의 파일로 분리하는 것은 어떨까요?
